
_dims_ = {
    "pressure" : {
        "base": "Pascal(Pa)",
        "Pascal(Pa)-bars(bar)": 100000,
        "Pascal(Pa)-megapascals(MPa)": 1573.66,
        "Pascal(Pa)-Kilopascals(kPa)": 102,
        "Pascal(Pa)-hectopascal(hPa)": 7.233,
        "Pascal(Pa)-millibar(mbar)": 3.597,
        "Pascal(Pa)-nanobar(nbar)": 0.225,
        "Pascal(Pa)-atmosphere(atm)": 0.102,
        "Pascal(Pa)-barye(ba)": 0.102,
        "Pascal(Pa)-ft of H20(ft H20)": 0.001,
        "Pascal(Pa)-in of Hg(in Hg)": 2.248e-4,
        "Pascal(Pa)-in of H20(in H20)": 2.248e-4,
        "Pascal(Pa)-mm of Hg(mm Hg)": 2.248e-4,
        "Pascal(Pa)-mm of H2O(mm H2O)": 2.248e-4,
        "Pascal(Pa)-ozf/in²(osi)": 2.248e-4,
        "Pascal(Pa)-pieze(pz)": 2.248e-4,
        "Pascal(Pa)-lb/ft²(psf)": 2.248e-4,
        "Pascal(Pa)-lb/in²(psi)": 2.248e-4,
    },

    "length" : {
        "base": "inch(in)",
        "inch(in)-centimetres(cm)": 2.54,
        "inch(in)-foot(ft)": 0.0833333,
        "inch(in)-yard(yd)": 0.0277778,
        "inch(in)-millimetre(mm)": 25.4,
        "inch(in)-metre(m)": 0.0254,
        "inch(in)-kilometre(km)": (2.54 * (10**(-5))),
        "inch(in)-microns(µm)": 25400,
        "inch(in)-amstrongs(Å)": 254000000,
        "inch(in)-mile(miles)": (1.57828 * (10 **(-5))),
    },

    "mass" : {
        "base": "Milligram(mg)",
        "Milligram(mg)-Decigram(dg)": 0.01,
        "Milligram(mg)-Centigram(Cg)": 0.1,
        "Milligram(mg)-Gram(g)": 0.001,
        "Milligram(mg)-Dekagram(dag)": 0.0001,
        "Milligram(mg)-Hectogram(hg)": 1.0e-5,
        "Milligram(mg)-Metric ton(t)": 1e-9,
        "Milligram(mg)-kilogram(kg)": 1e-6,
        "Milligram(mg)-Slug(slug)": 6.85218e-8,
        "Milligram(mg)-ounce(oz)": 3.5274e-5,
        "Milligram(mg)-pound(lb)": 2.20462e-6,
    },

    "volume" : {
        "base": "cubic metre(m³)",
        "cubic metre(m³)-cubic centimetre(cm³)": 1000000,
        "cubic metre(m³)-cubic inch(in³)": 61023.7,
        "cubic metre(m³)-cubic foot(ft³)": 35.3147,
        "cubic metre(m³)-quart(qt)": 1056.69,
        "cubic metre(m³)-litres(l)": 1000,
        "cubic metre(m³)-millilitres(ml)": 1000000,
        "cubic metre(m³)-U.S. gallon(gal)": 264.172,
        "cubic metre(m³)-U.K. gallon(gal)": 219.969,
        "cubic metre(m³)-Barrel(bbl)": 6.28981,
        "cubic metre(m³)-cubic decimetre(dm³)": 1e+9,
        "cubic metre(m³)-cubic millimetre(mm³)": 1000
    },

    "force" : {
        "base": "Newton",
        "Newton-dyne(dyn)": 100000,
        "Newton-grain-force(grf)": 1573.66,
        "Newton-gram-force(gf)": 102,
        "Newton-poundal(pdl)": 7.233,
        "Newton-ounce-force(ozf)": 3.597,
        "Newton-pound-force(lbf)": 0.225,
        "Newton-kilogram-force(kgf)": 0.102,
        "Newton-kilopond(kp)": 0.102,
        "Newton-sthène(sthène)": 0.001,
        "Newton-kip(kip)": 2.248e-4,
        "Newton-tonne-force(tf)": 2.248e-4,
    },

    "area" : {
        "base": "square metre(m²)",
        "square metre(m²)-square centimetre(cm²)": 10000,
        "square metre(m²)-square inch(in²)": 1550,
        "square metre(m²)-square foot(ft²)": 10.7639,
        "square metre(m²)-square yard(yd²)": 1.19599,
        "square metre(m²)-acre(acres)": 0.000247105,
        "square metre(m²)-quart(qt)": (1 * (10 ** (-6))),  # need to verify value and those below
        "square metre(m²)-square kilometre(km²)": (1 * (10 ** (-6))),
        "square metre(m²)-hectares(ha)": 0.0001,
        "square metre(m²)-square mile(miles²)": (3.86102 * (10 ** (-7))),
        "square metre(m²)-square millimetre(mm²)": 1000000
    },

    "work_and_energy" : {
        "base": "joule(J)",
        "joule(J)-calories(cal)":0.239,
        "joule(J)-kilocalories(kcal)":0.0002388,
        "joule(J)-kilojoules(kJ)":0.001,
        "joule(J)-electronvolt(eV)":6.241e18,
        "joule(J)-kilopondmetre(kp.m)":0.102,
        "joule(J)-kilowatt-hour(kWh)":2.778e-7,
        "joule(J)-therm(therm)":9.5e-9,
        "joule(J)-watt-hour(Wh)":0.0002778,
        "joule(J)-British Thermal Unit(Btu)":0.0009478,
        "joule(J)-Celsius heat unit(Chu)":0.0005266,
        "joule(J)-erg(erg)":1,
        "joule(J)-Hartree(Eh)":1,
        "joule(J)-quad(quad)":1,
        "joule(J)-rydberg(rydberg)":1,
        "joule(J)-specific fuel consumption(kgmp)":1,
        "joule(J)-thermochemical calorie(cal th)":1,
        "joule(J)-tonne of oil equivalent(toe)":1,
    },

    "density" : {
        "base": "gram per cubic metre(g/m³)",
        "gram per cubic metre(g/m³)-gram per cubic centimetre(g/cm³)":1,
        "gram per cubic metre(g/m³)-kilogram per cubic metre(kg/m³)":1,     
        "gram per cubic metre(g/m³)-milligram per cubic metre(mg/m³)":1,    
        "gram per cubic metre(g/m³)-ounce to gallon(UK)":1,
        "gram per cubic metre(g/m³)-ounce to gallon(US)":1,
        "gram per cubic metre(g/m³)-pound to gallon(lb/UK gal)":1,
        "gram per cubic metre(g/m³)-pound to gallon(lb/US gal)":1,
        "gram per cubic metre(g/m³)-pound to cubic foot(lb/cu.ft)":1,       
        "gram per cubic metre(g/m³)-pound to cubic inch(lb/cu.in)":1,       
        "gram per cubic metre(g/m³)-pound to cubic yard(lb/cu.yd)":1,       
        "gram per cubic metre(g/m³)-slug to cubic foot(slug/ft³)":1,   
    },

    "power" : {
        "base": "watt(W)",
        "watt(W)-kilowatts (kW)":1,
        "watt(W)-manpower":1,
        "watt(W)-abwatt (aW)":1,
        "watt(W)-air watt":1,
        "watt(W)-Btu per hour(Btu/h)":1,
        "watt(W)-Btu per minute(Btu/min)":1,
        "watt(W)-Btu per second(Btu/s)":1,
        "watt(W)-calories per hour(cal/h)":1,
        "watt(W)-calories per minute(cal/min)":1,
        "watt(W)-calories per second(cal/s)":1,
        "watt(W)-erg per second(erg/s)":1,
        "watt(W)-horse(ksi)":1,
        "watt(W)-horse(older definition)(ks)":1,
        "watt(W)-horsepower (HP)":1,
        "watt(W)-international watt(W int)":1,
        "watt(W)-kilocalories per hour(kcal/h)":1,
        "watt(W)-kilopond metres per second(kp.m/s)":1,
        "watt(W)-ponceletpound-force per second (lbf.ft/s)":1,
        "watt(W)-water horsepower(whp)":1,
    },

    "time" : {
        "base": "second(s)",
        "second(s)-minutes (min)":1,   
        "second(s)-hours (h)":1,       
        "second(s)-day (d)":1,
        "second(s)-millisecond (ms)":1,
        "second(s)-month(month)":1,    
        "second(s)-week(week)":1,      
        "second(s)-gregorian year":1,  
        "second(s)-helek(hl)":1,       
        "second(s)-Julian year":1,     
        "second(s)-leap-year":1,
        "second(s)-ordinary year":1,
        "second(s)-sidereal day":1,
        "second(s)-sidereal month":1,
        "second(s)-sidereal year":1,
        "second(s)-solar day":1,
        "second(s)-svedberg(S)":1,
        "second(s)-tropic year(a)":1,
    },

    "speed" : {
        "base": "metre per second(m/s)",
        "metre per second(m/s)-kilometres per hour (km/h)":1,
        "metre per second(m/s)-foot per hour (ft/h)":1,
        "metre per second(m/s)-knot (kn)":1,
        "metre per second(m/s)-metre per minute (m/min)":1,
        "metre per second(m/s)-mile per hour(MPH)":1,
        "metre per second(m/s)-speed of light(c)":1,
        "metre per second(m/s)-admiralty knot":1,
        "metre per second(m/s)-mach (Ma)":1,
        "metre per second(m/s)-polednikova tercie":1,
    },

    "plane_angle" : {
        "base": "radian (rad)",
        "radian (rad)-degrees (°)":1,
        "radian (rad)-centigrade":1,
        "radian (rad)-dilec":1,
        "radian (rad)-grade (g)":1,
        "radian (rad)-hora":1,
        "radian (rad)-minute":1,
        "radian (rad)-second":1,
        "radian (rad)-delostrelecky":1,
        "radian (rad)-matematical component(dc)":1,

    },

    "acceleration": {
        "base": "meter/square second(m/s²)",
        "meter/square second(m/s²)-decimeter/square second(dm/s²)":1,
        "meter/square second(m/s²)-kilometer/square second(km/s²)":1,       
        "meter/square second(m/s²)-hectometer/square second(hm/s²)":1,      
        "meter/square second(m/s²)-dekameter/square second(dam/s²)":1,      
        "meter/square second(m/s²)-centimeter/square second(cm/s²)":1,
        "meter/square second(m/s²)-millimeter/square second(mm/s²)":1,
        "meter/square second(m/s²)-micrometer/square second(μm)":1,
        "meter/square second(m/s²)-nanometer/square second(nm/s²)":1,       
        "meter/square second(m/s²)-picometer/square second(pm/s²)":1,
        "meter/square second(m/s²)-femtometer/square second(fm/s²)":1,
        "meter/square second(m/s²)-attometer/square second(am/s²)":1,       
        "meter/square second(m/s²)-gal (Gal)":1,
        "meter/square second(m/s²)-galileo (Gal)":1,
        "meter/square second(m/s²)-mile/square second (mi/s²)":1,
        "meter/square second(m/s²)-yard/square second(yd/s²)":1,
        "meter/square second(m/s²)-foot/square second (ft/s²)":1,
        "meter/square second(m/s²)-inch/square second (in/s²)":1,
        "meter/square second(m/s²)-Acceleration of gravity (g)":1,
    },

    "moment_of_inertia": {
        "base": "kilogram square meter(kg*m²)",
        "kilogram square meter(kg*m²)-kilogram square centimeter(kg*cm²)":1,"kilogram square meter(kg*m²)-kilogram square millimeter(kg*mm²)":1,"kilogram square meter(kg*m²)-gram square centimeter(g*cm²)":1,     
        "kilogram square meter(kg*m²)-gram square millimeter(g*mm²)":1,     
        "kilogram square meter(kg*m²)-kilogram-force meter square second(kgfm*s²)":1,
        "kilogram square meter(kg*m²)-kilogram-force centimeter square second(kgf*cm²)":1,
        "kilogram square meter(kg*m²)-ounce square inch (oz*in²)":1,        
        "kilogram square meter(kg*m²)-ounce-force inch square second(ozf*in²)":1,
        "kilogram square meter(kg*m²)-pound square foot (lb*ft²)":1,        
        "kilogram square meter(kg*m²)-pound-force foot square second(lbf*ft*s²)":1,
        "kilogram square meter(kg*m²)-pound square inch (lb*in²)":1,        
        "kilogram square meter(kg*m²)-pound-force inch square second(lbf*in*s²)":1,
        "kilogram square meter(kg*m²)-slug square foot(slug*ft²)":1,  
    },

    "kinematic_viscosity": {
        "base": "square metre per second(m²/s)",
        "square metre per second(m²/s)-square centimetre per second(cm²/s)":1,
        "square metre per second(m²/s)-square millimetre per second(mm²/s)":1,
        "square metre per second(m²/s)-centistoke":1,
        "square metre per second(m²/s)-Engler":1,
        "square metre per second(m²/s)-ft²/s":1,
        "square metre per second(m²/s)-in²/s":1,
        "square metre per second(m²/s)-Redwood(1)":1,
        "square metre per second(m²/s)-Redwood(2)":1,
        "square metre per second(m²/s)-Saybolt Furol 122 °F":1,
        "square metre per second(m²/s)-Saybolt Furol 210 °F":1,
        "square metre per second(m²/s)-Saybolt Univ. 100 °F":1,
        "square metre per second(m²/s)-stoke":1,
    }, 

    "fuel_efficiency_to_mass": {
        "base": "joule/kilogram (J/kg)",
        "joule/kilogram (J/kg)-kilojoule/kilogram (kJ/kg)":1,
        "joule/kilogram (J/kg)-calorie (IT)/gram (cal/g)":1,
        "joule/kilogram (J/kg)-calorie (th)/gram":1,
        "joule/kilogram (J/kg)-(cal (th)/g)":1,
        "joule/kilogram (J/kg)-Btu (IT)/pound (Btu/lb)":1,
        "joule/kilogram (J/kg)-Btu (th)/pound (Btu (th)/lb)":1,
        "joule/kilogram (J/kg)-kilogram/joule (kg/J)":1,
        "joule/kilogram (J/kg)-kilogram/kilojoule (kg/kJ)":1,
        "joule/kilogram (J/kg)-gram/calorie (IT) (g/cal)":1,
        "joule/kilogram (J/kg)-gram/calorie (th) (g/cal (th))":1,
        "joule/kilogram (J/kg)-pound/Btu (IT) (lb/Btu)":1,
        "joule/kilogram (J/kg)-pound/Btu (th) (lb/Btu (th))":1,
        "joule/kilogram (J/kg)-pound/horsepower/hour(lb/hp/h)":1,
        "joule/kilogram (J/kg)-gram/horsepower (metric)/hour":1,
        "joule/kilogram (J/kg)-gram/kilowatt/hour":1,
    },

    "specific_volume_converter": {
        "base": "cubic meter/kilogram(m³/kg)",
        "cubic meter/kilogram(m³/kg)-cubic centimeter/gram(cm³/g)":1,
        "cubic meter/kilogram(m³/kg)-liter/kilogram (L/kg)":1,
        "cubic meter/kilogram(m³/kg)-liter/gram (L/g)":1,
        "cubic meter/kilogram(m³/kg)-cubic foot/kilogram (ft³/kg)":1,
        "cubic meter/kilogram(m³/kg)-cubic foot/pound (ft³/lb)":1,
        "cubic meter/kilogram(m³/kg)-gallon (US)/pound(gal/lb)":1,
        "cubic meter/kilogram(m³/kg)-gallon (UK)/pound(gal/lb)":1,
    },

    "fuel_efficiency_to_volume": {
        "base": "joule/cubic meter (J/m³)",
        "joule/cubic meter (J/m³)-joule/liter (J/L)":1,
        "joule/cubic meter (J/m³)-mega joule/cubic meter(mJ/m³)":1,
        "joule/cubic meter (J/m³)-kilojoule/cubic meter (kJ/m³)":1,
        "joule/cubic meter (J/m³)-kilocalorie (IT)/cubic meter(kcal/m³)":1,
        "joule/cubic meter (J/m³)-calorie (IT)/cubic centimeter(cal/cm³)":1,"joule/cubic meter (J/m³)-therm/cubic foot (therm/ft³)":1,
        "joule/cubic meter (J/m³)-therm/gallon (UK)":1,
        "joule/cubic meter (J/m³)-Btu (IT)/cubic foot (Btu/ft³)":1,
        "joule/cubic meter (J/m³)-Btu (th)/cubic foot(Btu/ft³)":1,
        "joule/cubic meter (J/m³)-CHU/cubic foot (CHU/ft³)":1,
        "joule/cubic meter (J/m³)-cubic meter/joule (m³/J)":1,
        "joule/cubic meter (J/m³)-liter/joule (L/J)":1,
        "joule/cubic meter (J/m³)-gallon (US)/horsepower":1,
        "joule/cubic meter (J/m³)-gallon (US)/horsepower":1,
    },

    "flow_rate": {
        "base": "cubic meter/kilogram(m³/kg)",        
        "cubic meter/kilogram(m³/kg)-cubic centimeter/gram(cm³/g)":1,       
        "cubic meter/kilogram(m³/kg)-liter/kilogram (L/kg)":1,
        "cubic meter/kilogram(m³/kg)-liter/gram (L/g)":1,
        "cubic meter/kilogram(m³/kg)-cubic foot/kilogram (ft³/kg)":1,       
        "cubic meter/kilogram(m³/kg)-cubic foot/pound (ft³/lb)":1,
        "cubic meter/kilogram(m³/kg)-gallon (US)/pound(gal/lb)":1,
        "cubic meter/kilogram(m³/kg)-gallon (UK)/pound(gal/lb)":1,
    },

    "electrical_resistance": {
        "base": "ohm (Ω)",
        "ohm (Ω)-abohm(aΩ)":1,
        "ohm (Ω)-statohm(sΩ)":1,
    },

    "dynamic_viscosity": {
        "base": "newton second per square metre (N.s/m²)",
        "newton second per square metre (N.s/m²)-dyne second per square centimetre(dyne.s/cm²)":1,
        "newton second per square metre (N.s/m²)-gram per centimetre-second(g/cm.s)":1,
        "newton second per square metre (N.s/m²)-mN.s/m²":1,
        "newton second per square metre (N.s/m²)-poise":1,
        "newton second per square metre (N.s/m²)-pound.s/foot²":1,
        "newton second per square metre (N.s/m²)-pound/foot.s":1,
        "newton second per square metre (N.s/m²)-poundal.s/foot²":1,
        "newton second per square metre (N.s/m²)-slug/foot.s":1,
    },

    "mass_flow_rate": {
        "base": "kilogram/second (kg/s)",
        "kilogram/second (kg/s)-gram/second (g/s)":1,
        "kilogram/second (kg/s)-gram/minute (g/min)":1,
        "kilogram/second (kg/s)-gram/hour (g/h)":1,
        "kilogram/second (kg/s)-gram/day (g/d)":1,
        "kilogram/second (kg/s)-milligram/minute (mg/min)":1,
        "kilogram/second (kg/s)-milligram/hour (mg/h)":1,
        "kilogram/second (kg/s)-milligram/day (mg/d)":1,
        "kilogram/second (kg/s)-kilogram/minute (kg/min)":1,
        "kilogram/second (kg/s)-kilogram/hour (kg/h)":1,
        "kilogram/second (kg/s)-kilogram/day (kg/d)exagram/second (Eg/s)":1,"kilogram/second (kg/s)-petagram/second (Pg/s)":1,
        "kilogram/second (kg/s)-teragram/second (Tg/s)":1,
        "kilogram/second (kg/s)-gigagram/second (Gg/s)":1,
        "kilogram/second (kg/s)-megagram/second (Mg/s)":1,
        "kilogram/second (kg/s)-kilogram/second (kg/s)":1,
        "kilogram/second (kg/s)-gram/second (g/s)":1,
        "kilogram/second (kg/s)-gram/minute (g/min)":1,
        "kilogram/second (kg/s)-gram/hour (g/h)":1,
        "kilogram/second (kg/s)-gram/day (g/d)":1,
        "kilogram/second (kg/s)-milligram/minute (mg/min)":1,
        "kilogram/second (kg/s)-milligram/hour (mg/h)":1,
        "kilogram/second (kg/s)-milligram/day (mg/d)":1,
        "kilogram/second (kg/s)-kilogram/minute (kg/min)":1,
        "kilogram/second (kg/s)-kilogram/hour (kg/h)":1,
        "kilogram/second (kg/s)-kilogram/day (kg/d)":1,
        "kilogram/second (kg/s)-exagram/second (Eg/s)":1,
        "kilogram/second (kg/s)-petagram/second (Pg/s)":1,
        "kilogram/second (kg/s)-teragram/second (Tg/s)":1,
        "kilogram/second (kg/s)-gigagram/second (Gg/s)":1,
        "kilogram/second (kg/s)-megagram/second (Mg/s)":1,
        "kilogram/second (kg/s)-hectogram/second (hg/s)":1,
        "kilogram/second (kg/s)-dekagram/second (dag/s)":1,
        "kilogram/second (kg/s)-decigram/second (dg/s)":1,
        "kilogram/second (kg/s)-centigram/second (cg/s)":1,
        "kilogram/second (kg/s)-milligram/second (mg/s)":1,
        "kilogram/second (kg/s)-microgram/second (µg/s)":1,
        "kilogram/second (kg/s)-ton (metric)/second (t/s)":1,
        "kilogram/second (kg/s)-ton (metric)/minute (t/min)":1,
        "kilogram/second (kg/s)-ton (metric)/hour (t/h)":1,
        "kilogram/second (kg/s)-ton (metric)/day (t/d)":1,
        "kilogram/second (kg/s)-ton (short)/hour (ton (US)/h)":1,
        "kilogram/second (kg/s)-pound/second (lb/s)":1,
        "kilogram/second (kg/s)-pound/minute (lb/min)":1,
        "kilogram/second (kg/s)-pound/hour (lb/h)":1,
        "kilogram/second (kg/s)-pound/day (lb/d)":1,
    },

    "molarity": {
        "base": "mol/cubic meter (mol/m³)",
        "mol/cubic meter (mol/m³)-mol/liter (mol/L)":1,
        "mol/cubic meter (mol/m³)-mol/cubic centimeter(mol/cm³)":1,
        "mol/cubic meter (mol/m³)-mol/cubic millimeter(mol/mm³)":1,
        "mol/cubic meter (mol/m³)-kilomol/cubic meter(mol/m³)":1,
        "mol/cubic meter (mol/m³)-kilomol/liter (kmol/L)":1,
        "mol/cubic meter (mol/m³)-kilomol/cubic centimeter(kmol/cm³)":1,
        "mol/cubic meter (mol/m³)-kilomol/cubic millimeter(kmol/mm³)":1,
        "mol/cubic meter (mol/m³)-millimol/cubic meter(mmol/m³)":1,
        "mol/cubic meter (mol/m³)-millimol/liter (mmol/L)":1,
        "mol/cubic meter (mol/m³)-millimol/cubic centimeter(mmol/cm³)":1,
        "mol/cubic meter (mol/m³)-millimol/cubic millimeter(mmol/mm³)":1,
    },

    "molality": {
        "base": "kilogram/liter (kg/L)",
        "kilogram/liter (kg/L)-gram/liter (g/L)":1,
        "kilogram/liter (kg/L)-milligram/liter (mg/L)":1,
        "kilogram/liter (kg/L)-part/million (ppm)":1,
        "kilogram/liter (kg/L)-grain/US gallon (gr/gal(US))":1,
        "kilogram/liter (kg/L)-grain/UK gallon (gr/gal(UK))":1,
        "kilogram/liter (kg/L)-pound/US gallon (lb/gal(US))":1,
        "kilogram/liter (kg/L)-pound/UK gallon (lb/gal(UK))":1,
        "kilogram/liter (kg/L)-pound/million gallon(US)":1,
        "kilogram/liter (kg/L)-pound/million gallon(UK)":1,
        "kilogram/liter (kg/L)-pound/cubic foot (lb/ft³)":1,
    },

    "surface_tension": {
        "base": "Newton/metre (N/m)",
        "Newton/metre (N/m)-millinewton/metre (mN/m)":1,      
        "Newton/metre (N/m)-gram-force/centimetre (grf/cm)":1,
        "Newton/metre (N/m)-dyne/centimetre (dyn/cm)":1,
        "Newton/metre (N/m)-erg/square millimetre (erg/mm²)":1,
        "Newton/metre (N/m)-erg/square centimetre (erg/cm²)":1,
        "Newton/metre (N/m)-poundal/inch (pdl/in)":1,
        "Newton/metre (N/m)-pound-force/inch (lbf/in)":1,
    },

    "specific_heat_capacity": {
        "base": "joule/kilogram/K (J/(kg*K))",
        "joule/kilogram/K (J/(kg*K))-joule/kilogram/°C (J/(kg*°C))":1,
        "joule/kilogram/K (J/(kg*K))-joule/gram/°C (J/(g*°C))":1,
        "joule/kilogram/K (J/(kg*K))-kilojoule/kilogram/K (kJ/(kg*K)":1,    
        "joule/kilogram/K (J/(kg*K))-kilojoule/kilogram/°C (kJ/(kg*°C)":1,  
        "joule/kilogram/K (J/(kg*K))-calorie (IT)/gram/°C (cal/(g*°C))":1,  
        "joule/kilogram/K (J/(kg*K))-calorie (IT)/gram/°F (cal/(g*°F))":1,  
        "joule/kilogram/K (J/(kg*K))-calorie (th)/gram/°C (cal/(g*°C))":1,  
        "joule/kilogram/K (J/(kg*K))-kilocalorie (th)/gram/°C (kcal/(g*°C))":1,
        "joule/kilogram/K (J/(kg*K))-kilocalorie (IT)/gram/K (kcal/(g*K))":1,
        "joule/kilogram/K (J/(kg*K))-kilocalorie (th)/gram/K (kcal/(g*K))":1,
        "joule/kilogram/K (J/(kg*K))-kilocalorie (IT)/gram/°C (kcal/(g*°C))":1,
        "joule/kilogram/K (J/(kg*K))-kilogram-force metre/kilogram/K (kgrf*m/(kg*K)":1,
        "joule/kilogram/K (J/(kg*K))-pound-force foot/pound/°R (lbf*ft/(lb*°R))":1,
        "joule/kilogram/K (J/(kg*K))-Btu (IT)/pound/°F (Btu(IT)/(lb*°F))":1,"joule/kilogram/K (J/(kg*K))-Btu (th)/pound/°F (Btu(th)/(lb*°F))":1,"joule/kilogram/K (J/(kg*K))-Btu (IT)/pound/°R (Btu(IT)/(lb*°R))":1,"joule/kilogram/K (J/(kg*K))-Btu (th)/pound/°R (Btu(th)/(lb*°R))":1,"joule/kilogram/K (J/(kg*K))-Btu (IT)/pound/°C (Btu(IT)/(lb*°C))":1,"joule/kilogram/K (J/(kg*K))-CHU/pound/°C (CHU/(lb*°C))":1,
    },

    "heat_transfer_coefficient": {
        "base": "watt/square metre/K (W/(m²*K))",
        "watt/square metre/K (W/(m²*K))-watt/square metre/%b0C (W/(m²*%b0C))":1,
        "watt/square metre/K (W/(m²*K))-joule/second/square metre/K (J/(m²*K*s))":1,
        "watt/square metre/K (W/(m²*K))-calorie (IT)/second/square centimetre/%b0C (cal/(cm²*%b0C*s))":1,
        "watt/square metre/K (W/(m²*K))-kilocalorie (IT)/hour/square metre/%b0C (kcal/(m²*%b0C*h))":1,
        "watt/square metre/K (W/(m²*K))-kilocalorie (IT)/hour/square foot/%b0C (kcal/(ft²*%b0C*h))":1,
        "watt/square metre/K (W/(m²*K))-Btu (IT)/second/square foot/%b0F (Btu/(ft²*%b0F*s))":1,
        "watt/square metre/K (W/(m²*K))-Btu (th)/second/square foot/%b0F (Btu/(ft²*%b0F*s))":1,
        "watt/square metre/K (W/(m²*K))-Btu (IT)/hour/square foot/%b0F (Btu/(ft²*%b0F*h))":1,
        "watt/square metre/K (W/(m²*K))-Btu (th)/hour/square foot/%b0F (Btu/(ft²*%b0F*h))":1,
        "watt/square metre/K (W/(m²*K))-CHU/hour/square foot/%b0C (CHU/(ft²*%b0C*h))":1,
    }
}


_units_ = {
    "length": ["inch(in)", "centimetres(cm)", "foot(ft)", "yard(yd)", "millimetre(mm)",
                       "metre(m)", "kilometre(km)", "microns(µm)", "amstrongs(Å)", "mile"],
    
    "area": ["square metre(m²)", "square centimetre(cm²)", "square inch(in²)", "square foot(ft²)", "square yard(yd²)",
                       "acre(acres)", "quart(qt)", "square kilometre(km²)", "hectares(ha)", "square mile(miles²)", "square millimetre(mm²)"],

    "volume": ["cubic metre(m³)", "cubic centimetre(cm³)", "cubic inch(in³)", "cubic foot(ft³)", "quart(qt)",
                        "litres(l)", "millilitres(ml)", "U.S. gallon(gal)", "U.K. gallon(gal)", "Barrel(bbl)",
                        "cubic decimetre(dm³)", "cubic millimetre(mm³)"],
    
    "mass": ["Milligram(mg)", "Decigram(dg)", "Centigram(Cg)", "Gram(g)", "Dekagram(dag)", "Hectogram(hg)",
                       "Metric ton(t)", "kilogram(kg)", "Slug(slug)", "ounce(oz)", "pound(lb)"],
    
    "force": ["Newton", "dyne(dyn)", "Decigram(dg)", "grain-force(grf)", "gram-force(gf)", "poundal(pdl)", "ounce-force(ozf)",
                       "pound-force(lbf)", "kilogram-force(kgf)", "kilopond(kp)", "sthène(sthène)", "kip(kip)", "tonne-force(tf)"],

    "pressure": ["Pascal(Pa)", "bars(bar)", "megapascals(MPa)", "Kilopascals(kPa)", "hectopascal(hPa)", "millibar(mbar)",
                       "nanobar(nbar)", "atmosphere(atm)", "barye(ba)", "ft of H20(ft H20)", "in of Hg(in Hg)", "in of H20(in H20)",
                       "mm of Hg(mm Hg)", "mm of H2(mm H2O)", "ozf/in²(osi)", "pieze(pz)", "lb/ft²(psf)",
                       "lb/in²(psi)"],
    
    "work_and_energy": ["joule(J)", "calories(cal)", "kilocalories(kcal)", "kilojoules(kJ)", "electronvolt(eV)", "kilopondmetre(kp.m)",
                       "kilowatt-hour(kWh)", "therm(therm)", "watt-hour(Wh)", "British Thermal Unit(Btu)", "Celsius heat unit(Chu)", "erg(erg)",
                       "Hartree(Eh)", "quad(quad)", "rydberg(rydberg)", "specific fuel consumption(kgmp)", "thermochemical calorie(cal th)",
                       "tonne of oil equivalent(toe)"],
    
    "power": ["watt(W)", "kilowatts (kW)", "manpower", "abwatt (aW)", "air watt", "Btu per hour(Btu/h)",
                       "Btu per minute(Btu/min)", "Btu per second(Btu/s)", "calories per hour(cal/h)",
                       "calories per minute(cal/min)", "calories per second(cal/s)", "erg per second(erg/s)",
                       "horse(ksi)", "horse(older definition)(ks)", "horsepower (HP)", "international watt(W int)",
                       "kilocalories per hour(kcal/h)", "kilopond metres per second(kp.m/s)", "poncelet"
                       "pound-force per second (lbf.ft/s)", "water horsepower(whp)"],
    
    "density": ["gram per cubic metre(g/m³)", "gram per cubic centimetre(g/cm³)", "kilogram per cubic metre(kg/m³)", "milligram per cubic metre(mg/m³)", "ounce to gallon(UK)", "ounce to gallon(US)",
                       "pound to gallon(lb/UK gal)", "pound to gallon(lb/US gal)", "pound to cubic foot(lb/cu.ft)", "pound to cubic inch(lb/cu.in)", "pound to cubic yard(lb/cu.yd)", "slug to cubic foot(slug/ft³)"],
    
    "time": ["second(s)", "minutes (min)", "hours (h)", "day (d)", "millisecond (ms)", "month(month)",
                       "week(week)", "gregorian year", "helek(hl)", "Julian year", "leap-year", "ordinary year",
                       "sidereal day", "sidereal month", "sidereal year", "solar day", "svedberg(S)", "tropic year(a)"],

    "speed": ["metre per second(m/s)", "kilometres per hour (km/h)", "foot per hour (ft/h)", "knot (kn)", "metre per minute (m/min)", "mile per hour(MPH)",
                       "speed of light(c)", "admiralty knot", "mach (Ma)", "polednikova tercie"],

    "plane_angle": ["radian (rad)", "degrees (°)", "centigrade", "dilec", "grade (g)", "hora",
                       "minute", "second", "delostrelecky", "matematical component(dc)"],
    
    "angular_velocity": ["radian/second(rad/s)", "radian/day (rad/d)", "radian/hour (rad/h)", "radian/minute (rad/min)",
                       "degree/day (°/d)", "degree/hour (°/h)", "degree/minute (°/min)", "degree/second (°/s)",
                       "revolution/day (r/d)", "revolution/hour (r/h)", "revolution/minute (r/min)", "revolution/second (r/s)"],
        
    "acceleration": [
            "meter/square second(m/s²)", "decimeter/square second(dm/s²)", "kilometer/square second(km/s²)",
            "hectometer/square second(hm/s²)", "dekameter/square second(dam/s²)", "centimeter/square second(cm/s²)",
            "millimeter/square second(mm/s²)", "micrometer/square second(μm)", "nanometer/square second(nm/s²)",
            "picometer/square second(pm/s²)", "femtometer/square second(fm/s²)", "attometer/square second(am/s²)",
            "gal (Gal)", "galileo (Gal)", "mile/square second (mi/s²)", "yard/square second(yd/s²)",
            "foot/square second (ft/s²)", "inch/square second (in/s²)", "Acceleration of gravity (g)"
    ],

    "moment_of_inertia": ["kilogram square meter(kg*m²)", "kilogram square centimeter(kg*cm²)",
        "kilogram square millimeter(kg*mm²)", "gram square centimeter(g*cm²)", "gram square millimeter(g*mm²)",
        "kilogram-force meter square second(kgfm*s²)",
        "kilogram-force centimeter square second(kgf*cm²)", "ounce square inch (oz*in²)",
        "ounce-force inch square second(ozf*in²)",
        "pound square foot (lb*ft²)", "pound-force foot square second(lbf*ft*s²)",
        "pound square inch (lb*in²)", "pound-force inch square second(lbf*in*s²)", "slug square foot(slug*ft²)"],
    
    "kinematic_viscosity": ["square metre per second(m²/s)", "square centimetre per second(cm²/s)", "square millimetre per second(mm²/s)",
                        "centistoke", "Engler", "ft²/s", "in²/s", "Redwood(1)", "Redwood(2)", "Saybolt Furol 122 °F", "Saybolt Furol 210 °F",
                        "Saybolt Univ. 100 °F", "stoke"
                    ],

    "fuel_efficiency_to_mass": ["joule/kilogram (J/kg)", "kilojoule/kilogram (kJ/kg)", "calorie (IT)/gram (cal/g)",
                       "calorie (th)/gram", "(cal (th)/g)", "Btu (IT)/pound (Btu/lb)", "Btu (th)/pound (Btu (th)/lb)",
                       "kilogram/joule (kg/J)", "kilogram/kilojoule (kg/kJ)", "gram/calorie (IT) (g/cal)",
                       "gram/calorie (th) (g/cal (th))", "pound/Btu (IT) (lb/Btu)", "pound/Btu (th) (lb/Btu (th))",
                       "pound/horsepower/hour(lb/hp/h)", "gram/horsepower (metric)/hour", "gram/kilowatt/hour"],

    "specific_volume_converter": ["cubic meter/kilogram(m³/kg)", "cubic centimeter/gram(cm³/g)", "liter/kilogram (L/kg)",
                       "liter/gram (L/g)", "cubic foot/kilogram (ft³/kg)", "cubic foot/pound (ft³/lb)",
                       "gallon (US)/pound(gal/lb)", "gallon (UK)/pound(gal/lb)"],
    
    "fuel_efficiency_to_volume": ["joule/cubic meter (J/m³)", "joule/liter (J/L)", "mega joule/cubic meter(mJ/m³)",
                       "kilojoule/cubic meter (kJ/m³)", "kilocalorie (IT)/cubic meter(kcal/m³)",
                       "calorie (IT)/cubic centimeter(cal/cm³)", "therm/cubic foot (therm/ft³)",
                       "therm/gallon (UK)", "Btu (IT)/cubic foot (Btu/ft³)", "Btu (th)/cubic foot(Btu/ft³)",
                       "CHU/cubic foot (CHU/ft³)", "cubic meter/joule (m³/J)", "liter/joule (L/J)", "gallon (US)/horsepower", "gallon (US)/horsepower"],

    "flow_rate": ["cubic metre per second(m³/s)", "cubic metre per day((m³/day)", "cubic metre per hour(m³/h)", "cubic metre per minute(m³/min)",
                        "liter per second(L/s)", "svedrup(m³)"],

    "electrical_resistance": ["ohm (Ω)", "abohm(aΩ)", "statohm(sΩ)"],

    "dynamic_viscosity": ["newton second per square metre (N.s/m²)", "dyne second per square centimetre(dyne.s/cm²)", "gram per centimetre-second(g/cm.s)",
                    "mN.s/m²", "poise", "pound.s/foot²", "pound/foot.s", "poundal.s/foot²", "slug/foot.s"],

    "mass_flow_rate": ["kilogram/second (kg/s)", "gram/second (g/s)", "gram/minute (g/min)", "gram/hour (g/h)", "gram/day (g/d)", "milligram/minute (mg/min)",
                         "milligram/hour (mg/h)", "milligram/day (mg/d)", "kilogram/minute (kg/min)", "kilogram/hour (kg/h)", "kilogram/day (kg/d)" "exagram/second (Eg/s)", 
                         "petagram/second (Pg/s)", "teragram/second (Tg/s)", "gigagram/second (Gg/s)", 
                        "megagram/second (Mg/s)", "kilogram/second (kg/s)", "gram/second (g/s)", "gram/minute (g/min)", "gram/hour (g/h)", "gram/day (g/d)", 
                        "milligram/minute (mg/min)", "milligram/hour (mg/h)", "milligram/day (mg/d)", "kilogram/minute (kg/min)", "kilogram/hour (kg/h)", "kilogram/day (kg/d)", "exagram/second (Eg/s)", 
                        "petagram/second (Pg/s)", "teragram/second (Tg/s)", "gigagram/second (Gg/s)", "megagram/second (Mg/s)", "hectogram/second (hg/s)", 
                        "dekagram/second (dag/s)", "decigram/second (dg/s)", "centigram/second (cg/s)", "milligram/second (mg/s)", "microgram/second (µg/s)", 
                        "ton (metric)/second (t/s)", "ton (metric)/minute (t/min)", "ton (metric)/hour (t/h)", "ton (metric)/day (t/d)", "ton (short)/hour (ton (US)/h)", 
                        "pound/second (lb/s)", "pound/minute (lb/min)", "pound/hour (lb/h)", "pound/day (lb/d)"],

    "molarity": ["mol/cubic meter (mol/m³)", "mol/liter (mol/L)", "mol/cubic centimeter(mol/cm³)", "mol/cubic millimeter(mol/mm³)", "kilomol/cubic meter(mol/m³)", "kilomol/liter (kmol/L)", "kilomol/cubic centimeter(kmol/cm³)", 
                        "kilomol/cubic millimeter(kmol/mm³)", "millimol/cubic meter(mmol/m³)", "millimol/liter (mmol/L)", "millimol/cubic centimeter(mmol/cm³)", "millimol/cubic millimeter(mmol/mm³)"],
    
    "molality": ["kilogram/liter (kg/L)", "gram/liter (g/L)", "milligram/liter (mg/L)", "part/million (ppm)", "grain/US gallon (gr/gal(US))", 
                        "grain/UK gallon (gr/gal(UK))", "pound/US gallon (lb/gal(US))", "pound/UK gallon (lb/gal(UK))", "pound/million gallon(US)",
                         "pound/million gallon(UK)", "pound/cubic foot (lb/ft³)"],

    "surface_tension": ["Newton/metre (N/m)", "millinewton/metre (mN/m)", "gram-force/centimetre (grf/cm)", "dyne/centimetre (dyn/cm)", "erg/square millimetre (erg/mm²)", 
                        "erg/square centimetre (erg/cm²)", "poundal/inch (pdl/in)", "pound-force/inch (lbf/in)"],

    "specific_heat_capacity": ["joule/kilogram/K (J/(kg*K))", "joule/kilogram/°C (J/(kg*°C))", "joule/gram/°C (J/(g*°C))", "kilojoule/kilogram/K (kJ/(kg*K)", "kilojoule/kilogram/°C (kJ/(kg*°C)",
                        "calorie (IT)/gram/°C (cal/(g*°C))", "calorie (IT)/gram/°F (cal/(g*°F))", "calorie (th)/gram/°C (cal/(g*°C))", "kilocalorie (th)/gram/°C (kcal/(g*°C))",
                        "kilocalorie (IT)/gram/K (kcal/(g*K))", "kilocalorie (th)/gram/K (kcal/(g*K))", "kilocalorie (IT)/gram/°C (kcal/(g*°C))", "kilogram-force metre/kilogram/K (kgrf*m/(kg*K)",
                        "pound-force foot/pound/°R (lbf*ft/(lb*°R))", "Btu (IT)/pound/°F (Btu(IT)/(lb*°F))", "Btu (th)/pound/°F (Btu(th)/(lb*°F))", "Btu (IT)/pound/°R (Btu(IT)/(lb*°R))", 
                        "Btu (th)/pound/°R (Btu(th)/(lb*°R))", "Btu (IT)/pound/°C (Btu(IT)/(lb*°C))", "CHU/pound/°C (CHU/(lb*°C))"],

    "heat_transfer_coefficient": ["watt/square metre/K (W/(m²*K))", "watt/square metre/%b0C (W/(m²*%b0C))", "joule/second/square metre/K (J/(m²*K*s))", "calorie (IT)/second/square centimetre/%b0C (cal/(cm²*%b0C*s))", "kilocalorie (IT)/hour/square metre/%b0C (kcal/(m²*%b0C*h))",
                        "kilocalorie (IT)/hour/square foot/%b0C (kcal/(ft²*%b0C*h))", "Btu (IT)/second/square foot/%b0F (Btu/(ft²*%b0F*s))", "Btu (th)/second/square foot/%b0F (Btu/(ft²*%b0F*s))", "Btu (IT)/hour/square foot/%b0F (Btu/(ft²*%b0F*h))",
                        "Btu (th)/hour/square foot/%b0F (Btu/(ft²*%b0F*h))", "CHU/hour/square foot/%b0C (CHU/(ft²*%b0C*h))"],
}


def dict_dim_conversions(dim):
    return _dims_.get(dim)

def list_units(unit):
    return _units_.get(unit)

